In [89]:
import pandas as pd
import numpy as np
from scipy import stats

### Q1.  A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions.


In [90]:
df=pd.read_csv("C:/Users/DELL 5459/Downloads/excelr/Assignment/3 Hypothesis Testing/Cutlets.csv")

In [91]:
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [92]:
df.mean()

Unit A    7.019091
Unit B    6.964297
dtype: float64

In [93]:
df.var()

Unit A    0.083179
Unit B    0.117924
dtype: float64

In [94]:
df.std()

Unit A    0.288408
Unit B    0.343401
dtype: float64

We have to perform 2-sample t-test

In [95]:
#Ho: Mu1 = Mu2  Average of diameter of unit A is equal to Average of diameter of unit B
#Ha: Mu1 =! Mu2 Average of diameter of unit A is not equal to Average of diameter of unit B 

In [96]:
Ttest, p_value= stats.ttest_ind(df['Unit A'], df['Unit B'])

In [97]:
p_value

0.4722394724599501

In [98]:
Ttest

0.7228688704678061

In [99]:
if p_value < 0.05  :   #alpha= 0.05
    print('We reject Null Hypothesis')
else:
    print('We accept Null Hypothesis')

We accept Null Hypothesis


There is no significance different between the diameters of Unit A and Unit B.

### Q2. A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
### Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.¶

In [100]:
df2= pd.read_csv('C:/Users/DELL 5459/Downloads/excelr/Assignment/3 Hypothesis Testing/LabTAT.csv')

In [101]:
df2.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [102]:
df2.mean()

Laboratory 1    178.361583
Laboratory 2    178.902917
Laboratory 3    199.913250
Laboratory 4    163.682750
dtype: float64

In [103]:
df2.std()

Laboratory 1    13.173594
Laboratory 2    14.957114
Laboratory 3    16.539033
Laboratory 4    15.085080
dtype: float64

#### ANOVA one way test

As there  are more than 2 discrete variables and output TAT is a continuous variable. Hence we will go with Anova one way test.

Ho: Average TAT for all the samples is same.

Ha: Average TAT for all the sample is not same.

In [104]:
test, p_value= stats.f_oneway(df2.iloc[:,0], df2.iloc[:,1], df2.iloc[:,2], df2.iloc[:,3])

In [105]:
p_value

2.1156708949992414e-57

In [106]:
if p_value < 0.05 :    #alpha = 0.05
    print('We reject Null Hypothesis')
else:
    print('We Accept Null hypothesis')

We reject Null Hypothesis


The significance level is 5% so, alpha= 0.05

There is a significance difference in the average TAT for all the labs.

### Q3. Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

In [107]:
df3 = pd.read_csv('C:/Users/DELL 5459/Downloads/excelr/Assignment/3 Hypothesis Testing/BuyerRatio.csv')
df3.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

Inputs are discrete variables(east,west,noth,south). Output is also discrete.

We are trying to find out if proportion of male and female are similar or not across the regions We proceed with chi-square test.

### Chi- Square Test.

Ho : Proportion of Male and Female are same.


Ha : Proportion of Male and female are not same.

In [108]:
df3.columns

Index(['Observed Values', 'East', 'West', 'North', 'South'], dtype='object')

In [109]:
df4= df3.drop(['Observed Values'], axis=1)

In [110]:
df4

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [111]:
observed_values = df4.values
print('Observed Values:-  \n', observed_values)

Observed Values:-  
 [[  50  142  131   70]
 [ 435 1523 1356  750]]


In [112]:
val = stats.chi2_contingency(df4)

In [113]:
val

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [114]:
expected_values = val[3]

In [115]:
expected_values

array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
       [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]])

In [116]:
no_of_rows= len(df4.iloc[0:2,:0])
no_of_columns= len(df4.iloc[0,0:4])
dof= (no_of_rows - 1) * (no_of_columns - 1)   #finding degree of freedom
print('degree of freedom:- ', dof)
alpha= 0.05

degree of freedom:-  3


In [117]:
from scipy.stats import chi2

chi_square = sum([(o-e)**2./e for o,e in zip(observed_values, expected_values)])
chi_square_statistic = chi_square[0]+ chi_square[1]

In [118]:
print('chi-square_statistic:- ', chi_square_statistic)

chi-square_statistic:-  1.5152956451130446


In [119]:
critical_value = chi2.ppf(q=1-alpha, df=dof)  #p_value is alpha so q_value is 1-alpha.In this case q is 0.95.
print('critical_value:- ', critical_value)

critical_value:-  7.814727903251179


In [120]:
#calculating p_value
p_value = 1-chi2.cdf(x=chi_square_statistic,df=dof)
print('p_value:- ',p_value)
print("significance_level:- ",alpha)
print("Degrees of Freedom:- ",dof)

p_value:-  0.6787446296467897
significance_level:-  0.05
Degrees of Freedom:-  3


In [121]:
if chi_square_statistic >= critical_value :
    print('Proportions of Male and Female are not same.')
else:
    print('Proportion of Male and Female are same.')
    
if p_value <= alpha:
    print('Proportion of Male and Female are not same.')
else:
    print('proportion of Male and Female are same.')

Proportion of Male and Female are same.
proportion of Male and Female are same.


The significance level is 5% so, alpha= 0.05

Therefore P should be > 0.05 to consider Null hypothesis(Ho).

Hence proportion of male and female across the region are same.

### Q4.  TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

In [122]:
df5 = pd.read_csv('C:/Users/DELL 5459/Downloads/excelr/Assignment/3 Hypothesis Testing/CostomerOrderForm.csv')

In [123]:
df5.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [124]:
Phillippines = df5.Phillippines.value_counts()
Phillippines

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [125]:
Indonesia = df5.Indonesia.value_counts()
Indonesia

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [126]:
Malta = df5.Malta.value_counts()
Malta

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [127]:
India = df5.India.value_counts()
India

Error Free    280
Defective      20
Name: India, dtype: int64

In [128]:
ErrorFree = [271,267,269,280]
Defective = [29,33,31,20]

In [129]:
chistats_defective = stats.chi2_contingency([ErrorFree,Defective])
print('Test t=%f p-value=%f' % (chistats_defective[0], chistats_defective[1]))
print('Interpret by p-Value')
if chistats_defective[1] < 0.05:
  print('Reject null hypothesis')
else:
  print('Fail to reject null hypothesis')

Test t=3.858961 p-value=0.277102
Interpret by p-Value
Fail to reject null hypothesis
